# Generated by Django 6.0.5 on 2026-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='audio_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='has_ebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='has_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_pages_json',
            field=models.TextField(blank=True, help_text='JSON list of preview page URLs', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='quote',
            field=models.TextField(blank=True, help_text='Quote from the book shared by user', null=True),
        ),
    ]
